select * from customerpurchases limit 20

--total revenue generated by male vs female customers
select gender, sum(purchase_amount) as total_revenue
from customerpurchases
group by gender

--customers who used discount but still spend more than the avg purchase amount
select customer_id, discount_applied, purchase_amount
from customerpurchases
where purchase_amount>(select avg(purchase_amount) from customerpurchases) and discount_applied='Yes'

--what are the top 5 products with the highest avg review rating
select item_purchased, round(avg(review_rating::numeric), 2) as avg_rating
from customerpurchases
group by item_purchased
order by avg(review_rating) DESC limit 5

--compare the avg purchase amounts between standard and express shipping
select shipping_type, round(avg(purchase_amount), 2) as avg_purchase_amount
from customerpurchases
where shipping_type in ('Standard', 'Express')
group by shipping_type

--do subscribed customers spend more? compare avg spend and total revenue between subscribers 
--and non-subscribers
select subscription_status, round(avg(purchase_amount), 2) as avg_spend, sum(purchase_amount) as total_revenue
from customerpurchases
group by subscription_status

--which 5 products have the highest percentage of purchases with discounts applied
select item_purchased,
round(100*sum
(case when discount_applied='Yes' then 1 else 0 end)/count(*), 2) as percentage_of_purchases
from customerpurchases
group by item_purchased
order by percentage_of_purchases DESC limit 5

--segment customers into new, returning and loyal based on their total number of previous purchases, 
--and show count of each segment (1-new, 2 to 10-returning, >10-loyal)
with cust_type as (select customer_id, previous_purchases, 
case when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as cust_segment
from customerpurchases)
select cust_segment, count(*) from cust_type group by cust_segment

--what are the top 3 most purchased products within each category
with item_counts as (
select item_purchased, category, count(customer_id) as no_of_customers,
row_number()over(partition by category order by count(customer_id) DESC) as item_rank
from customerpurchases
group by item_purchased, category
)
select category, item_purchased, item_rank from item_counts where item_rank<=3

--are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status, count(customer_id)
from customerpurchases
where previous_purchases>5
group by subscription_status

--what is the revenue contribution of each age grp
select age_group, sum(purchase_amount) as total_revenue 
from customerpurchases 
group by age_group
order by total_revenue DESC